// <auto-generated />
using System;
using Caiti.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Caiti.Migrations
{
    [DbContext(typeof(CaitiDbContext))]
    [Migration("20221009062013_Test89")]
    partial class Test89
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29");

            modelBuilder.Entity("Caiti.Models.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Office_hours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("Caiti.Models.Subject", b =>
                {
                    b.Property<Guid>("Id_Subject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name_Subject")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Obligatory")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfessorID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Subject");

                    b.HasIndex("ProfessorID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Caiti.Models.Subject", b =>
                {
                    b.HasOne("Caiti.Models.Professor", null)
                        .WithMany("Subjects")
                        .HasForeignKey("ProfessorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
